name: Deploy to AWS

on:
  push:
    branches:
      - main # Change to your main branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t depaul-cloud-project .

      - name: Tag Docker image
        run: |
          docker tag depaul-cloud-project:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/depaul-cloud-project:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/depaul-cloud-project:latest

      - name: Deploy to ECS
        uses: aws-actions/ecs-deploy-task-definition@v1
        with:
          cluster: ${{ secrets.ECS_CLUSTER_NAME }} # Replace with your ECS cluster name
          service: ${{ secrets.ECS_SERVICE_NAME }} # Replace with your ECS service name
          task-definition: ${{ secrets.ECS_TASK_DEFINITION }} # Specify your task definition
          wait-for-service-stability: true
